### ISSUE TITLE
Mis translation in french

### ISSUE THREAD

**Issue by ColonelMoutarde** [php/doc-fr#356]
From manual page: https://php.net/function.random-int

---

but if I click on contribute to documentation, the translation of the text is correct : "Generates cryptographic random integers that are suitable for use where unbiased results are critical, such as when shuffling a deck of cards for a poker game. "

**Comment by devnexen** [comment]
It does that with other non english versions too.

**Comment by ColonelMoutarde** [comment]
It's normal ?

**Comment by devnexen** [comment]
It s definitively a bug but not in the translation texts. Maybe @girgias has a better idea what is going on.

**Comment by adoy** [comment]
I may be wrong, but I think the reason for this issue is that the documentation is out of sync, and some files in the original documentation have been relocated. For instance, in the French documentation, the file random-int.xml is located in the csprng folder, while in the English documentation, it is in the random folder. To resolve this, we would need to ensure that all files are up-to-date and synchronized before moving them.

**Comment by ColonelMoutarde** [comment]
There may be the same problem on other pages.

**Comment by adoy** [comment]
If you look at [this page](http://doc.php.net/revcheck.php?p=oldfiles&lang=fr
) you should see all the files in the french doc that do not have their exact equivalent in the english one, so those should be problematic.
